#配置DataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tan610322
    url: jdbc:mysql://localhost:3306/db_iot_hub_ihorn?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    dbcp:
      initial-size: 5
      max-idle: 100
      min-idle: 3
      max-wait-millis: 50000
#配置mybatis
mybatis:
  type-aliases-package: com.txymybatis.pojo
  mapper-locations: classpath:mapper/*.xml
#配置PageHelper
pagehelper:
  helper­dialect: mysql